export const mockPermitRequests = [
  {
    request_id: 'PMT-2024-001',
    applicant: {
      id: 'APP-001',
      name: 'John Anderson',
      email: 'john.anderson@email.com',
      phone: '+1 (555) 123-4567',
      address: '123 Main Street, Springfield, IL 62701',
    },
    permit_type: 'building',
    submitted_data: {
      project_type: 'Residential Addition',
      estimated_cost: 45000,
      square_footage: 500,
      contractor_name: 'ABC Construction LLC',
    },
    submitted_at: '2024-12-20T09:30:00Z',
    status: 'pending',
  },
  {
    request_id: 'PMT-2024-002',
    applicant: {
      id: 'APP-002',
      name: 'Sarah Mitchell',
      email: 'sarah.mitchell@business.com',
      phone: '+1 (555) 234-5678',
      address: '456 Commerce Ave, Springfield, IL 62702',
    },
    permit_type: 'business',
    submitted_data: {
      business_name: 'Fresh Bites Cafe',
      business_type: 'Food Service',
      employees: 8,
      operating_hours: '7 AM - 9 PM',
    },
    submitted_at: '2024-12-19T14:15:00Z',
    status: 'pending',
  },
  {
    request_id: 'PMT-2024-003',
    applicant: {
      id: 'APP-003',
      name: 'Michael Chen',
      email: 'mchen@events.org',
      phone: '+1 (555) 345-6789',
      address: '789 Park Lane, Springfield, IL 62703',
    },
    permit_type: 'event',
    submitted_data: {
      event_name: 'Community Music Festival',
      expected_attendees: 500,
      event_date: '2025-01-15',
      venue: 'Central Park Amphitheater',
    },
    submitted_at: '2024-12-18T11:45:00Z',
    status: 'pending',
  },
  {
    request_id: 'PMT-2024-004',
    applicant: {
      id: 'APP-004',
      name: 'Emily Rodriguez',
      email: 'e.rodriguez@mail.com',
      phone: '+1 (555) 456-7890',
      address: '321 Oak Drive, Springfield, IL 62704',
    },
    permit_type: 'vehicle',
    submitted_data: {
      vehicle_type: 'Commercial Truck',
      vehicle_weight: '26000 lbs',
      purpose: 'Delivery Services',
      duration: '12 months',
    },
    submitted_at: '2024-12-17T16:20:00Z',
    status: 'pending',
  },
  {
    request_id: 'PMT-2024-005',
    applicant: {
      id: 'APP-005',
      name: 'David Thompson',
      email: 'david.t@contractor.com',
      phone: '+1 (555) 567-8901',
      address: '567 Industrial Blvd, Springfield, IL 62705',
    },
    permit_type: 'building',
    submitted_data: {
      project_type: 'Commercial Renovation',
      estimated_cost: 125000,
      square_footage: 2000,
      contractor_name: 'Thompson & Sons Construction',
    },
    submitted_at: '2024-12-16T10:00:00Z',
    status: 'pending',
  },
];